server:
  port: 8080
proxy:
  name: test
  servletUrl: /*
  targetUrl: https://cn.bing.com
logging:
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) --- %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
  level:
    root: error
    top.meethigher: info
    # 验证所有bean的加载顺序
    org.springframework.beans.factory: debug