server:
  port: 8080
proxy:
  name: test
  servletUrl: /*
  targetUrl: https://cn.bing.com
logging:
  level:
    root: error
    top.meethigher: info
    # 验证所有bean的加载顺序
    org.springframework.beans.factory: debug