server:
  port: 8080
proxy:
  name: test
  servletUrl: /*
  targetUrl: https://bing.com
logging:
  level:
    root: info
    top.meethigher: info
    # 验证所有bean的加载顺序
    org.springframework.beans.factory: error